# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default: task --list-all
  i: npm install
  t: npm run tsc -- -b
  d: npm run dev
  c: npm run biome -- check --fix
  f: npm run biome -- format --fix
  r: npm run generate-routes
  p: npm run build
  z: git archive --format=zip --output=repo.zip HEAD
  a: npm run shadcn -- add {{.CLI_ARGS}}
  g: npm run openapi-ts
  sync:
    dotenv: ['.env.development']
    cmd: curl -k {{.VITE_API_BASE_URL}}/openapi.yml -o ./src/features/api/openapi.yml
    requires:
      vars:
        - VITE_API_BASE_URL
